//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeManagement.Data.DataStructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormTypes
    {
        public FormTypes()
        {
            this.Forms = new HashSet<Forms>();
        }
    
        public int FormTypeId { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual FormTypes FormTypes1 { get; set; }
        public virtual FormTypes FormTypes2 { get; set; }
        public virtual ICollection<Forms> Forms { get; set; }
    }
}
