//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeManagement.Data.DataStructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissions
    {
        public int PermissionId { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int MenuId { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Menus Menus { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Users Users { get; set; }
    }
}
