//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeManagement.Data.DataStructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Priorities
    {
        public Priorities()
        {
            this.Works = new HashSet<Works>();
        }
    
        public int PriorityId { get; set; }
        public string Priority { get; set; }
    
        public virtual ICollection<Works> Works { get; set; }
    }
}
