//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeManagement.Data.DataStructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.UsersRoles = new HashSet<UsersRoles>();
            this.Works = new HashSet<Works>();
            this.WorksUsersStatus = new HashSet<WorksUsersStatus>();
            this.Permissions = new HashSet<Permissions>();
            this.FormStatuses = new HashSet<FormStatuses>();
            this.EventTo = new HashSet<EventTo>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<UsersRoles> UsersRoles { get; set; }
        public virtual ICollection<Works> Works { get; set; }
        public virtual ICollection<WorksUsersStatus> WorksUsersStatus { get; set; }
        public virtual ICollection<Permissions> Permissions { get; set; }
        public virtual ICollection<FormStatuses> FormStatuses { get; set; }
        public virtual ICollection<EventTo> EventTo { get; set; }
    }
}
