//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeManagement.Data.DataStructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorksUsersStatus
    {
        public int WorkUserStatusId { get; set; }
        public int WorkId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> WorkStatusId { get; set; }
        public Nullable<int> AssignedUserId { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Works Works { get; set; }
        public virtual WorkStatuses WorkStatuses { get; set; }
    }
}
